name: example-basic
# This workflow represents a set of basic End-to-End tests
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        # to add with token 
        
      - name: Check
        #if : "contains(github.event.head_commit.message, '[gitTest, merge]')"
        run : |
          echo "[LOG] It contains [gitTest], will update to other repo"
          cd ../../../../gitTest/
          git fetch
          echo "[LOG] Git fetch"
          git pull origin master
          echo "[LOG] Git pull"
          
